### ISSUE TITLE
Missing setup.py mentioned in the book

### ISSUE THREAD

**Issue by SheikhSajid** [dreilly369/AppliedMathForSecurityBook#2]
In **Chapter 1**, under the **Advanced Setup** section, the book mentions a `setup.py` file intended to help readers in setting up the environment. However, I couldn't find it in the repository. In fact, there is no Chapter 1 folder at all.

![image](https://github.com/dreilly369/AppliedMathForSecurityBook/assets/9877529/bff6e0c9-4abf-41a6-81bb-2e4f7a2e9d54)

**Comment by dreilly369** [comment]
Nowadays the use of setup.py is discouraged. Instead, the two theory chapters have a requirements.txt which contain the pinned versions of the libraries I used during development. I recommend starting a virtual environment from Anaconda and trying to install the packages without pinned versions first. You should only downgrade the versions if you run into trouble with any of the examples.
You can create an environment from the requirements.txt file with a command like:
`conda create --name my-env-name --file requirements.txt`
